/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Green LED---GPIOD pin12
int main(void)
{
	SystemInit();
	//enable GPIOD clock ---RCC AHB1ENR[3]=1
	RCC->AHB1ENR |=BV(3);
	//config GPIOD.12 as output---MODER[25:24]-01
	GPIOD->MODER &=~BV(25);
	GPIOD->MODER |=BV(24);
	//config GPIOD.12 as pushpull---OTYPER[12]-1
	GPIOD->OTYPER |=BV(12);
	//config GPIOD.12 as low-speed----OSPEEDR[25:24]-00
	GPIOD->OSPEEDR &=~(BV(25) |BV(24));
	//config GPIOD.12 with no pullup & pulldown resistor PUPDR[25:24]--11
	GPIOD->PUPDR |=(BV(25)| BV(24));

	while(1){
		//Led On ---GPIOD.12 =1---ODR[12] =1
		GPIOD->ODR |=BV(12);
		//Delay
		DelayMs(500);
		 //Led Off---GPIOD.12---ODR[12]=0
		GPIOD->ODR &=~BV(12);
		//Delay
		DelayMs(500);
	}
	return 0;
}

